[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "agent-transport"
version = "0.2.0"
description = "Transport binding layer for agent:// protocol"
authors = ["Yaswanth Narvaneni <yaswanth@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/WizardOfAgents/agent-uri"
repository = "https://github.com/WizardOfAgents/agent-uri"
documentation = "https://agent-uri.readthedocs.io"
keywords = ["agent", "transport", "protocol", "networking"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
packages = [{include = "agent_transport"}]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"
websocket-client = "^1.7.0"
sseclient-py = "^1.8.0"
agent-uri-parser = {path = "../uri-parser", develop = true}
agent-descriptor = {path = "../descriptor", develop = true}

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
pytest-asyncio = "^0.21.0"
black = "^23.12.0"
isort = "^5.13.0"
flake8 = "^6.1.0"
mypy = "^1.8.0"

[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
profile = "black"
known_first_party = ["agent_transport"]

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
testpaths = ["agent_transport/tests"]
python_files = ["test_*.py"]
addopts = [
    "--strict-markers",
    "--cov=agent_transport",
    "--cov-report=term-missing",
    "--cov-report=html",
]